//  Firebase
//==========
import {initializeApp} from 'https://www.gstatic.com/firebasejs/9.15.0/firebase-app.js'
import {
  getDatabase,
  ref,
  push,
  onValue, remove,
} from 'https://www.gstatic.com/firebasejs/9.15.0/firebase-database.js'

import {useEffect, useState} from 'react'
import {nanoid} from 'nanoid';
import Item from './components/item.jsx';
import './css/App.css'

/*
 Todo: 
   - Fix the id bug 
   - change the useEffect to run every time the database is updated
   - add buttons that add or subtract how of each item to get
   - add a check box to each li item and when checked cross the li items
    from the lis
   - create a button that removes all items from the list 
 DONE - create a function that adds the current input's value to the item list
 DONE - create a button that removes or crosses the items once purchased
 */



function App() {
  //  Firebase 
  //==========
  const appSettings = {
    databaseURL: 'https://playground-e9327-default-rtdb.firebaseio.com/'
  }
  const app = initializeApp(appSettings)
  const database = getDatabase(app)
  const shoppingCartDB = ref(database, 'shoppingList')

  //  State
  //=======
  const [itemList, setItemList] = useState([])  
  const [currentItem, setCurrentItem] = useState({
    id: '',
    name: '',
  })

  useEffect(() => {
    onValue(shoppingCartDB, (snapshot) => {
          const listArr = Object.values(snapshot.val())
          setItemList(listArr)
          console.log(listArr)
        })
  }, [])



  //  Functions
  //===========

  /*
     newItem() is triggered when the user types in a new item 
     in the input field. It sets the currentItem state to an object 
     that contains a unique id generated using the nanoid() function 
     and the name of the item that was entered by the user.
   */
  function newItem(e) {
    setCurrentItem({
      id: nanoid(),
      name: e.target.value,
    })
  }

  /* 
    addItem() is called when the user clicks on the "Add Item" button. 
    If the name of the currentItem is not an empty string, it adds 
    the item to the shoppingCartDB and updates the itemList and 
    currentItem states accordingly. 
  */
  function addItem() {
    if (currentItem.name !== '') {
      push(shoppingCartDB, currentItem)
      setCurrentItem({ di: '', name: '',})
    }
  }

  /*
    allItems() contains an array of JSX elements generated by mapping
    through the itemList state. It uses the Item component to render 
    each item in the list, passing the key, id, name, and remove props.
  */
  const allItems = itemList.map(item =>
      <Item 
          key={item.id} 
          id={item.id}
          item={item.name} 
          remove={removeItem}
      />,
  )

  /*
    removeItem(id) is called when the user clicks on the "Remove" 
    button for an item. It removes the item from the itemList state 
    and deletes it from the shoppingList database by creating a 
    reference to the item using its id and calling the remove() function.
  */
  function removeItem(id) {
    setItemList(prevState => prevState.filter(item => item.id !== id ))
    const itemRef = ref(database, `shoppingList/${id}`)
    remove(itemRef)
  }

  // HTML
  //=====
  return (
      <div className="App">
        <h1 className="title">Shopping List</h1>

        <div className="container">
          <input
            className="input--field"
            placeholder="add item to the list"
            name="input"
            value={currentItem.name}
            onChange={(e) => newItem(e)}
          />
          <i className="fa-solid fa-cart-shopping fa-lg icon"></i>
        </div>

        <ul>
          {allItems}
        </ul>

        <button
            className="button--add"
            onClick={addItem}
        >
          Add Item
        </button>

      </div>
  )
}

export default App
